# -------------------------------------------------------------------------
#' 
#' This script will perform the immunobridging analysis in "SA55 broadly 
#' neutralizes SARS-CoV-2 and robustly prevents viral escape by JN.1 sublineages"
#' 
# -------------------------------------------------------------------------

### (1) Generate models first from COVID-mAb-prophylaxis repository:
# https://github.com/david-s-khoury/COVID19-mAb-prophylaxis/
# OR load model data utilized in this analysis from "/model-data" directory in step 4

# (2) load packages -----
library(readxl)
library(ggtext)
library(patchwork)
library(reshape2)
library(Matrix)
library(lme4)
library(mvtnorm)
library(stringr)
library(lmec)
library(nlme)
library(multcomp)
library(tidyverse)
library(RColorBrewer)

# (3) define functions and set model parameters -----
geometric_mean <- function(x) {
  if (any(x <= 0, na.rm = TRUE)) {
    return(NaN) # Geometric mean is undefined for non-positive values
  }
  prod(x, na.rm = TRUE)^(1/length(x))
}

#efficacy function is from "COVID-mAb-prophylaxis" repository above
efficacy <- function(d,par,model=use_efficacy_model){
  if(model=="logistic"){
    # 3 parameters: maximum (transform specified in max_transform), slope (log-transformed), IC50 (log-transformed)
    m <- ifelse(max_transform=="exp",exp(par[1]),ifelse(max_transform=="1-exp",1-exp(par[1]),ifelse(max_transform=="1-abs",1-abs(par[1]),par[1])))
    m/(1+(2*m-1)*exp(-exp(par[2])*(log10(d)-log10(exp(par[3])))))
  }else if(model=="single hit"){
    # 1 parameter for slope
    1-exp(-par*log10(d))
  }else if(model=="powerlaw"){
    # parameters: slope (as for single hit model), exponent
    1-exp(-par[1]*log10(d)^par[2])
  }else if(model=="threshold"){
    # parameters: threshold for jump, efficacy before jump, efficacy after jump
    ifelse(d<par[1],par[2],par[3])
  }else if(model=="slope threshold"){
    # parameters: threshold for jump, efficacy before jump, efficacy after jump, slope before jump
    ifelse(d<par[1],par[2]+par[4]*log10(d),par[3])
  }else if(model=="double logistic"){
    # parameters: threshold, maximum efficacy, slope before threshold, slope after threshold
    # same transformations as for the logistic model, i.e. log-transform on slopes and specified transform on maximum
    m <- ifelse(max_transform=="exp",exp(par[2]),ifelse(max_transform=="1-exp",1-exp(par[2]),ifelse(max_transform=="1-abs",1-abs(par[2]),par[2])))
    ifelse(d<par[1],m/(m+exp(-exp(par[3])*log10(d))),m/(m+exp(-exp(par[3])*log10(par[1])-exp(par[4])*(log10(d)-log10(par[1])))))
  }else if(model=="logistic with slope 1"){
    # parameters: maximum efficacy, IC50
    # same transformations as for the logistic model, i.e. log-transformed IC50 and specified transform on maximum
    m <- ifelse(max_transform=="exp",exp(par[1]),ifelse(max_transform=="1-exp",1-exp(par[1]),ifelse(max_transform=="1-abs",1-abs(par[1]),par[1])))
    m/(1+(2*m-1)*exp(-(log10(d)-log10(exp(par[2])))))
  }else if(model=="logistic with max 1"){
    # parameters: slope, IC50
    # same transformations as for the logistic model, i.e. log-transformed slope and IC50
    1/(1+exp(-exp(par[1])*(log10(d)-log10(exp(par[2])))))
  }
}
efficacy <- Vectorize(efficacy, vectorize.args = "d")


# (4) load model data, output generated by file 03_Dose-response-curve.R from above repo -----

load("model-data/Model-data-analysis-model_2-3-25.RData")
load("model-data/Best-fit-all-models_2-3-25.RData")
load("model-data/Best-fit-analysis-model_2-3-25.RData")

# (5) Input mAb concentration data----
#Pemivibart data are obtained from:
#Schmidt, P., Li, Y. & Popejoy, M. Immunobridging for Pemivibart, a Monoclonal Antibody for Prevention of Covid-19. New England Journal of Medicine 391, 1860–1862 (2024).
pem_conc <- tibble( day = c(1,28,90), concentration = c(
              1510352,  #Day 1 pemivibart concentration in ng/mL
              468339,   #Day 28 concentration
              211789    #Day 90 concentration
        ))

#Estimated SA55 concentrations, see raw-data/mAb-concentration.xlsx
sa55_conc <- tibble( day = c(1,28,90),
              c900 = c(  #900mg initial dose
                144187,  #Day 1 concentration in ng/mL
                96193,   #Day 28 concentration
                39256),   #Day 90 concentration
              
              c600 = c( #600mg initial dose
                96124,  #Day 1 pemivibart concentration in ng/mL
                64128,   #Day 28 concentration
                26171),   #Day 90 concentration
              
              c300 = c(  #300mg initial dose
                48062,  #Day 1 pemivibart concentration in ng/mL
                32064,   #Day 28 concentration
                13085),   #Day 90 concentration
              
              c150 = c(  #150mg initial dose
                24031,  #Day 1 pemivibart concentration in ng/mL
                16032,   #Day 28 concentration
                6543),   #Day 90 concentration
              
)

# (6) Input mAb ic50 data-----
sa55_ic50 <- read_xlsx("raw-data/SA55-IC50-values-2025-1-31.xlsx") #add new in vitro IC50s to this file
pem_ic50 <- read_xlsx("raw-data/Pemivibart-IC50-values-2025-1-10.xlsx") #add new in vitro IC50s to this file

# (7) Create variant-normalized concentration tables -----
#Create Pemivibart Lab_variant IC50 index table
pem_index <- pem_ic50 %>%
  pivot_longer(cols = -Variant, names_to = "Lab", values_to = "ic50") %>%
  mutate(mAb = "pemivibart") %>%
  mutate(dose = 4500) %>%
  mutate(index = paste(Lab, Variant, mAb, sep = "_")) %>%
  select(index, Lab, Variant, mAb, dose, ic50)


#Create  SA55 Lab_variant IC50 index table
sa55_index <- sa55_ic50 %>%
  pivot_longer(cols = -Variant, names_to = "Lab", values_to = "ic50") %>%
  mutate(mAb = "sa55") %>%
  mutate(dose=NA) %>%
  mutate(index = paste(Lab, Variant, mAb, sep = "_")) %>%
  select(index, Lab, Variant, mAb, dose, ic50)
sa55_i900 <- sa55_index %>%
  mutate(index=paste0(index,"_c900")) %>%
  mutate(dose = 900)
sa55_i600 <- sa55_index %>%
  mutate(index=paste0(index,"_c600")) %>%
  mutate(dose=600)
sa55_i300 <- sa55_index %>%
  mutate(index=paste0(index,"_c300")) %>%
  mutate(dose=300)
sa55_i150 <- sa55_index %>%
  mutate(index=paste0(index,"_c150")) %>%
  mutate(dose=150)
sa55_index <- bind_rows(sa55_i900,sa55_i600,sa55_i300,sa55_i150)

#Combine index table
mAb_index<-bind_rows(pem_index,sa55_index)

#Add to pemivibart concentration table values normalized by Lab_variant IC50 values
for (i in 1:nrow(pem_index)) {
  normalizedIC50 <- pem_index$index[i] #column titles for normalized IC50s
  pem_conc[[normalizedIC50]] <- pem_conc$concentration / pem_index$ic50[i]
}
pem_norm<-pem_conc[,-(1:2)]

#Add to sa55 concentration table values normalized by Lab_variant IC50 values
sa55_c900 <- sa55_conc %>% select(day,c900)
sa55_c600 <- sa55_conc %>% select(day,c600)
sa55_c300 <- sa55_conc %>% select(day,c300)
sa55_c150 <- sa55_conc %>% select(day,c150)

for (i in 1:nrow(sa55_i900)) {
  normalizedIC50 <- sa55_i900$index[i] #column titles for normalized IC50s
  sa55_c900[[normalizedIC50]] <- sa55_c900$c900 / sa55_i900$ic50[i]
}
sa55_c900<-sa55_c900[,-(1:2)]
for (i in 1:nrow(sa55_i600)) {
  normalizedIC50 <- sa55_i600$index[i] #column titles for normalized IC50s
  sa55_c600[[normalizedIC50]] <- sa55_c600$c600 / sa55_i600$ic50[i]
}
sa55_c600<-sa55_c600[,-(1:2)]
for (i in 1:nrow(sa55_i300)) {
  normalizedIC50 <- sa55_i300$index[i] #column titles for normalized IC50s
  sa55_c300[[normalizedIC50]] <- sa55_c300$c300 / sa55_i300$ic50[i]
}
sa55_c300<-sa55_c300[,-(1:2)]
for (i in 1:nrow(sa55_i150)) {
  normalizedIC50 <- sa55_i150$index[i] #column titles for normalized IC50s
  sa55_c150[[normalizedIC50]] <- sa55_c150$c150 / sa55_i150$ic50[i]
}
sa55_c150<-sa55_c150[,-(1:2)]
sa55_norm<-bind_cols(sa55_c900,sa55_c600,sa55_c300,sa55_c150)

#Combine variant-normalized concentration tables for both mAbs
mAb_norm<-bind_cols(pem_norm,sa55_norm)

# (8) Use model to estimate efficacy from normalized mAb concentrations------
efficacy_est <- efficacy(mAb_norm,param_best,model=use_efficacy_model)

# (9) Generate point table to plot --------
points<-tibble(
  labels = names(mAb_norm))
points<- points %>% 
  mutate(Lab = as_factor(mAb_index$Lab)) %>%
  mutate(Variant = as_factor(mAb_index$Variant)) %>%
  mutate(mAb = as_factor(mAb_index$mAb)) %>%
  mutate(dose = mAb_index$dose) %>%
  mutate(tx = as_factor(paste(mAb,dose,sep="_"))) %>%
  mutate(eff_d1 = as.numeric(efficacy_est[1,])) %>%
  mutate(eff_d28 = as.numeric(efficacy_est[2,])) %>%
  mutate(eff_d90 = as.numeric(efficacy_est[3,])) %>%
  mutate(dose_d1 = as.numeric(mAb_norm[1,])) %>%
  mutate(dose_d28 = as.numeric(mAb_norm[2,])) %>%
  mutate(dose_d90 = as.numeric(mAb_norm[3,]))
  

### (10) PLOT Dose-response curves with mAb variant-normalized estimates ---------------

# set plotting parameters
plot_height<-4
plot_width<-4.5
title_size<-10
axis_size<-8
legend_size<-8

# assign colors and shapes
var_colors <- c("blue","red","limegreen", "purple","darkorange")
names(var_colors)<-c("JN.1","KP.2","KP.3","KP.3.1.1","XEC")

tx_colors<-c(
  #"pemivibart_4500"=as.character(var_colors[plot2var]),
  "pemivibart_4500"="blue",
  "sa55_150"="tomato",
  "sa55_300"="red",
  "sa55_600"="red3",
  "sa55_900"="firebrick4")

tx_shapes<-c("pemivibart_4500"=21,
             "sa55_150"=24,
             "sa55_300"=24,
             "sa55_600"=24,
             "sa55_900"=24)


### Figure 2B: pemivibart vs sa55 900mg against recent variants ----

#filter points to graph
chart_pts<-points %>% filter(Lab =="Liu" & Variant != "LB.1") %>%
  filter(tx == "pemivibart_4500" | tx == "sa55_900")

mAb_fit <- ggplot(chart_pts,aes(x=dose_d28,y=100*eff_d28,color=Variant, fill=Variant, shape=mAb)) +
  # model fit:
  geom_ribbon(data=model_data,inherit.aes=FALSE,aes(x=dose,ymin=100*lower, ymax=100*upper),fill="black", alpha = 0.1)+
  geom_line(data=model_data,inherit.aes=FALSE,aes(x=dose,y=100*fit),color="black") +
  
  #mAb efficacy zones
  geom_point(size=3,color="black") +
  scale_color_manual(values=var_colors)+
  scale_fill_manual(values=var_colors)+
  scale_shape_manual(values=c("pemivibart" = 21,
                              "sa55" = 24),
                     labels=c("pemivibart"="Pemivibart 4500mg",
                              "sa55"="SA55 900mg"))+
  #scale_color_brewer(palette = "YlOrRd",direction = 1) +
  geom_errorbarh(aes(xmin = dose_d90, xmax = dose_d1),height=2,linewidth=0.5) + #horizontal error bars
  #geom_errorbar(aes(ymin = 100*eff_d90, ymax = 100*eff_d1),width=0.05,linewidth=0.5) + #vertical error bars
  
  # axis, theme, etc.:
  scale_x_log10(breaks = 10^seq(0, 5, by = 1),
                minor_breaks = rep(c(2, 4, 6, 8), 6) * rep(10^seq(0, 5, by = 1), each = 4)) +
  scale_y_continuous(minor_breaks = seq(0, 100, 5),breaks=seq(0, 100, 10),labels=seq(0, 100, 10),expand = c(2e-2,1e-1)) +
  coord_cartesian(ylim = c(0,100), xlim = c(20,6e4)) +
  labs(x="Antibody concentration [fold in vitro IC50]",
       y="Efficacy [%]",
       title = "mAb therapy efficacy estimates") +
  guides(color = guide_legend(override.aes = list(fill = var_colors, shape = 22)))+
  guides(shape = guide_legend(override.aes = list(fill = "black")))+
  theme_bw() +
  theme(plot.title = element_text(size=title_size, face="bold",hjust=0.5),
        axis.text = element_text(size=axis_size),
        axis.title = element_text(size=title_size),
        legend.text = element_text(size=legend_size),
        legend.title = element_text(size=legend_size),
        panel.grid = element_line(colour="gray80", linewidth = 0.25),
        legend.position = "inside",
        legend.position.inside = c(0.95,0.05),
        legend.justification = c(1,0),
        legend.box.just = "right")
mAb_fit

# save plot:
cur_time <- format(Sys.time(),"h%H_m%M_s%S")
ggsave(glue::glue("output/mAb-dose-response_{Sys.Date()}_{cur_time}.pdf"),height=plot_height,width=plot_width,units="in",plot=mAb_fit)


### Figure S9: pemivibart vs sa55 concentration ranges for recent variants----
#filter points to graph
for (i in names(var_colors)) {plot2var = i   #to loop through all variants, saving plots

chart_pts<-points %>% filter(Lab =="Liu" & Variant == plot2var) %>%
  filter(mAb == "pemivibart" | mAb == "sa55")

dose_fit <- ggplot(chart_pts,aes(x=dose_d28,y=100*eff_d28,color=tx,shape=tx, fill=tx)) +
  # model fit:
  geom_ribbon(data=model_data,inherit.aes=FALSE,aes(x=dose,ymin=100*lower, ymax=100*upper),fill="black", alpha = 0.1)+
  geom_line(data=model_data,inherit.aes=FALSE,aes(x=dose,y=100*fit),color="black") +
  
  #mAb efficacy zones
  geom_point(size=3,color="black") +
  scale_fill_manual(values = tx_colors,
                     #aesthetics = c("fill"),
                     labels = c("pemivibart_4500"="Pemivibart 4500mg",
                                "sa55_150"="SA55 150mg",
                                "sa55_300"="SA55 300mg",
                                "sa55_600"="SA55 600mg",
                                "sa55_900"="SA55 900mg"))+
  scale_shape_manual(values = tx_shapes) +
  scale_color_manual(values = tx_colors) +
  geom_errorbarh(aes(xmin = dose_d90, xmax = dose_d1),height=2,linewidth=0.5) + #horizontal error bars
  #geom_errorbar(aes(ymin = 100*eff_d90, ymax = 100*eff_d1),width=0.05,linewidth=0.5) + #vertical error bars
  
  # axis, theme, etc.:
  scale_x_log10(breaks = 10^seq(0, 5, by = 1),
                minor_breaks = rep(c(2, 4, 6, 8), 6) * rep(10^seq(0, 5, by = 1), each = 4)) +
  scale_y_continuous(minor_breaks = seq(0, 100, 5),breaks=seq(0, 100, 10),labels=seq(0, 100, 10),expand = c(2e-2,1e-1)) +
  coord_cartesian(ylim = c(0,100), xlim = c(20,6e4)) +
  labs(x="Antibody concentration [fold in vitro IC50]",
       y="Efficacy [%]",
       title = paste("Efficacy estimate against",plot2var,sep=" ")) +
  guides(fill = guide_legend(override.aes = list(shape = tx_shapes)))+
  guides(shape="none",color="none")+
  theme_bw() +
  theme(plot.title = element_text(size=title_size, face="bold",hjust=0.5),
        axis.text = element_text(size=axis_size),
        axis.title = element_text(size=title_size),
        legend.text = element_text(size=legend_size),
        legend.title = element_blank(),
        panel.grid = element_line(colour="gray80", linewidth = 0.25),
        legend.position = "right",
        #legend.position.inside = c(0.95,0.05),
        #legend.box.just = "right",
        legend.justification = c(1,0))
dose_fit

# save plot:
cur_time <- format(Sys.time(),"h%H_m%M_s%S")
ggsave(glue::glue("output/{plot2var}-dose-response_{Sys.Date()}_{cur_time}.pdf"),height=plot_height,width=plot_width,units="in",plot=dose_fit)

} # end loop through all variants saving plots
